import { ApiHttpError } from '@/lib/api-response';
import { prisma } from '@/lib/prisma';

const CACHE_TTL_MS = 30_000;

interface WeeklySchemaCapability {
  ok: boolean;
  checkedAt: string;
  missing: string[];
  message: string | null;
}

let cache: { value: WeeklySchemaCapability; expiresAt: number } | null = null;

function nowIso() {
  return new Date().toISOString();
}

function asMessage(error: unknown): string {
  if (error instanceof Error) return error.message;
  return String(error);
}

export function isWeeklySchemaCapabilityError(error: unknown): boolean {
  if (!error || typeof error !== 'object') return false;
  const code = (error as { code?: unknown }).code;
  if (typeof code === 'string' && code === 'P2022') return true;

  const message = asMessage(error);
  return (
    /column .* does not exist/i.test(message) ||
    /relation .* does not exist/i.test(message) ||
    /type .* does not exist/i.test(message) ||
    /invalid input value for enum/i.test(message)
  );
}

async function collectMissingWeeklySchemaSignals(): Promise<{
  missing: string[];
  errorMessage: string | null;
}> {
  const missing = new Set<string>();
  let errorMessage: string | null = null;

  try {
    await prisma.$queryRawUnsafe(
      'SELECT "weekKey", "startsAt", "endsAt", "isAutoGenerated", "isClosed" FROM "Event" LIMIT 1'
    );
  } catch (error) {
    errorMessage = asMessage(error);
    missing.add('Event.weekly_columns');
  }

  try {
    await prisma.$queryRawUnsafe('SELECT "weekResetUtcOffset" FROM "WorkspaceSettings" LIMIT 1');
  } catch (error) {
    errorMessage = errorMessage || asMessage(error);
    missing.add('WorkspaceSettings.weekResetUtcOffset');
  }

  try {
    const rows = await prisma.$queryRawUnsafe<Array<{ value: string }>>(
      'SELECT unnest(enum_range(NULL::"ActivityMetricKey"))::text AS value'
    );
    const labels = new Set(rows.map((row) => String(row.value || '').toUpperCase()));
    if (!labels.has('FORT_DESTROYING')) {
      missing.add('ActivityMetricKey.FORT_DESTROYING');
    }
    if (!labels.has('KILL_POINTS_GROWTH')) {
      missing.add('ActivityMetricKey.KILL_POINTS_GROWTH');
    }
  } catch (error) {
    errorMessage = errorMessage || asMessage(error);
    missing.add('ActivityMetricKey.enum');
  }

  return {
    missing: [...missing],
    errorMessage,
  };
}

export async function getWeeklySchemaCapability(args?: {
  forceRefresh?: boolean;
}): Promise<WeeklySchemaCapability> {
  if (!args?.forceRefresh && cache && cache.expiresAt > Date.now()) {
    return cache.value;
  }

  const result = await collectMissingWeeklySchemaSignals();
  const capability: WeeklySchemaCapability = {
    ok: result.missing.length === 0,
    checkedAt: nowIso(),
    missing: result.missing,
    message: result.errorMessage,
  };

  cache = {
    value: capability,
    expiresAt: Date.now() + CACHE_TTL_MS,
  };

  return capability;
}

export async function assertWeeklySchemaCapability() {
  const capability = await getWeeklySchemaCapability();
  if (capability.ok) return capability;

  throw new ApiHttpError(
    'PRECONDITION_FAILED',
    'Weekly tracking schema is not fully migrated. Apply latest Prisma migrations and redeploy.',
    412,
    {
      checkedAt: capability.checkedAt,
      missing: capability.missing,
      message: capability.message,
    }
  );
}
