import { EventType, Prisma } from '@prisma/client';

interface EventStoreClient {
  event: {
    findFirst: Prisma.TransactionClient['event']['findFirst'];
    create: Prisma.TransactionClient['event']['create'];
  };
}

type DbClient = Prisma.TransactionClient | EventStoreClient;

async function getDbClient(tx?: DbClient): Promise<DbClient> {
  if (tx) return tx;
  const { prisma } = await import('@/lib/prisma');
  return prisma;
}

export interface WeekIdentity {
  weekKey: string;
  isoYear: number;
  isoWeek: number;
  startsAt: Date;
  endsAt: Date;
}

function toUtcDate(date: Date): Date {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
}

function startOfIsoWeekUtc(date: Date): Date {
  const d = toUtcDate(date);
  const day = (d.getUTCDay() + 6) % 7; // Monday=0
  d.setUTCDate(d.getUTCDate() - day);
  d.setUTCHours(0, 0, 0, 0);
  return d;
}

function endOfIsoWeekUtc(date: Date): Date {
  const start = startOfIsoWeekUtc(date);
  const end = new Date(start);
  end.setUTCDate(end.getUTCDate() + 7);
  return end;
}

function isoWeekYearAndNumber(date: Date): { isoYear: number; isoWeek: number } {
  const d = toUtcDate(date);
  const day = (d.getUTCDay() + 6) % 7; // Monday=0
  d.setUTCDate(d.getUTCDate() - day + 3); // Thursday
  const isoYear = d.getUTCFullYear();

  const firstThursday = new Date(Date.UTC(isoYear, 0, 4));
  const firstThursdayDay = (firstThursday.getUTCDay() + 6) % 7;
  firstThursday.setUTCDate(firstThursday.getUTCDate() - firstThursdayDay + 3);

  const weekDiff = d.getTime() - firstThursday.getTime();
  const isoWeek = 1 + Math.floor(weekDiff / (7 * 24 * 60 * 60 * 1000));
  return { isoYear, isoWeek };
}

export function getWeekIdentity(date = new Date()): WeekIdentity {
  const { isoYear, isoWeek } = isoWeekYearAndNumber(date);
  const startsAt = startOfIsoWeekUtc(date);
  const endsAt = endOfIsoWeekUtc(date);
  const weekKey = `${isoYear}-W${String(isoWeek).padStart(2, '0')}`;
  return {
    weekKey,
    isoYear,
    isoWeek,
    startsAt,
    endsAt,
  };
}

export function parseWeekKey(weekKey: string): { isoYear: number; isoWeek: number } | null {
  const match = String(weekKey || '')
    .trim()
    .match(/^(\d{4})-W(\d{2})$/);
  if (!match) return null;
  const isoYear = Number(match[1]);
  const isoWeek = Number(match[2]);
  if (!Number.isFinite(isoYear) || !Number.isFinite(isoWeek) || isoWeek < 1 || isoWeek > 53) {
    return null;
  }
  return { isoYear, isoWeek };
}

export function getWeekIdentityFromKey(weekKey: string): WeekIdentity | null {
  const parsed = parseWeekKey(weekKey);
  if (!parsed) return null;

  const jan4 = new Date(Date.UTC(parsed.isoYear, 0, 4));
  const week1Start = startOfIsoWeekUtc(jan4);
  const startsAt = new Date(week1Start);
  startsAt.setUTCDate(startsAt.getUTCDate() + (parsed.isoWeek - 1) * 7);
  const endsAt = new Date(startsAt);
  endsAt.setUTCDate(endsAt.getUTCDate() + 7);

  return {
    weekKey: `${parsed.isoYear}-W${String(parsed.isoWeek).padStart(2, '0')}`,
    isoYear: parsed.isoYear,
    isoWeek: parsed.isoWeek,
    startsAt,
    endsAt,
  };
}

function formatWeekDate(value: Date): string {
  return new Intl.DateTimeFormat('en-US', {
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  }).format(value);
}

export function buildWeeklyEventName(weekIdentity: WeekIdentity): string {
  return `Weekly Activity ${weekIdentity.weekKey} (${formatWeekDate(weekIdentity.startsAt)})`;
}

export async function ensureWeeklyEventForWorkspace(
  workspaceId: string,
  options?: {
    now?: Date;
    tx?: DbClient;
  }
) {
  const db = await getDbClient(options?.tx);
  const identity = getWeekIdentity(options?.now || new Date());

  const existing = await db.event.findFirst({
    where: {
      workspaceId,
      eventType: EventType.WEEKLY,
      weekKey: identity.weekKey,
    },
    orderBy: { createdAt: 'desc' },
  });

  if (existing) {
    return {
      event: existing,
      created: false,
      week: identity,
    };
  }

  const createdEvent = await db.event.create({
    data: {
      workspaceId,
      name: buildWeeklyEventName(identity),
      description: 'Auto-generated weekly roster tracking window (Monday 00:00 UTC).',
      eventType: EventType.WEEKLY,
      weekKey: identity.weekKey,
      startsAt: identity.startsAt,
      endsAt: identity.endsAt,
      isAutoGenerated: true,
      isClosed: false,
    },
  });

  return {
    event: createdEvent,
    created: true,
    week: identity,
  };
}

export async function findWeeklyEventByKey(
  workspaceId: string,
  weekKey: string,
  options?: {
    tx?: DbClient;
  }
) {
  const db = await getDbClient(options?.tx);
  return db.event.findFirst({
    where: {
      workspaceId,
      eventType: EventType.WEEKLY,
      weekKey: String(weekKey || '').trim(),
    },
    orderBy: { createdAt: 'desc' },
  });
}
