-- Weekly roster activity model: event week keys + per-alliance standards.

ALTER TABLE "Event"
ADD COLUMN IF NOT EXISTS "weekKey" TEXT,
ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "endsAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "isClosed" BOOLEAN NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS "Event_workspaceId_eventType_createdAt_idx"
ON "Event"("workspaceId", "eventType", "createdAt");

CREATE INDEX IF NOT EXISTS "Event_workspaceId_weekKey_idx"
ON "Event"("workspaceId", "weekKey");

CREATE UNIQUE INDEX IF NOT EXISTS "Event_workspaceId_eventType_weekKey_key"
ON "Event"("workspaceId", "eventType", "weekKey");

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ActivityMetricKey') THEN
    CREATE TYPE "ActivityMetricKey" AS ENUM ('POWER_GROWTH', 'CONTRIBUTION_POINTS');
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS "AllianceActivityStandard" (
  "id" TEXT NOT NULL,
  "workspaceId" TEXT NOT NULL,
  "allianceTag" TEXT NOT NULL,
  "allianceLabel" TEXT NOT NULL,
  "metricKey" "ActivityMetricKey" NOT NULL,
  "minimumValue" BIGINT NOT NULL,
  "isActive" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "AllianceActivityStandard_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "AllianceActivityStandard_workspaceId_allianceTag_metricKey_key"
ON "AllianceActivityStandard"("workspaceId", "allianceTag", "metricKey");

CREATE INDEX IF NOT EXISTS "AllianceActivityStandard_workspaceId_isActive_metricKey_idx"
ON "AllianceActivityStandard"("workspaceId", "isActive", "metricKey");

ALTER TABLE "AllianceActivityStandard"
ADD CONSTRAINT "AllianceActivityStandard_workspaceId_fkey"
FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
