import { NextRequest } from 'next/server';
import { WorkspaceRole } from '@prisma/client';
import { fail, handleApiError, ok, requireParam } from '@/lib/api-response';
import { prisma } from '@/lib/prisma';
import { authorizeWorkspaceAccess } from '@/lib/workspace-auth';
import { ensureWeeklyEventForWorkspace, findWeeklyEventByKey } from '@/lib/weekly-events';
import { invalidateServerCacheTags } from '@/lib/server-cache';
import { workspaceCacheTags } from '@/lib/cache-scopes';
import { assertWeeklySchemaCapability } from '@/lib/weekly-schema-guard';
import { drainMetricSyncBacklogOnRead } from '@/lib/metric-sync';
import { classifyEventType, getEventTypeDisplayLabel } from '@/lib/events/policy';

export const dynamic = 'force-dynamic';
export const revalidate = 0;

export async function GET(request: NextRequest) {
  try {
    const url = new URL(request.url);
    const workspaceId = requireParam(url.searchParams.get('workspaceId'), 'workspaceId');
    const weekKey = url.searchParams.get('weekKey')?.trim() || null;
    const autoCreate = url.searchParams.get('autoCreate') !== 'false';

    const auth = await authorizeWorkspaceAccess(request, workspaceId, WorkspaceRole.VIEWER);
    if (!auth.ok) {
      return fail(auth.code, auth.message, auth.code === 'UNAUTHORIZED' ? 401 : 403);
    }

    await assertWeeklySchemaCapability();
    await drainMetricSyncBacklogOnRead(workspaceId, 8);

    const weekly = weekKey
      ? await findWeeklyEventByKey(workspaceId, weekKey)
      : autoCreate
        ? (await ensureWeeklyEventForWorkspace(workspaceId)).event
        : null;

    if (!weekly) {
      return fail('NOT_FOUND', 'Weekly event not found.', 404);
    }

    return ok({
      id: weekly.id,
      name: weekly.name,
      description: weekly.description,
      eventType: weekly.eventType,
      eventTypeDisplay: getEventTypeDisplayLabel(weekly.eventType),
      eventClassification: classifyEventType(weekly.eventType),
      workspaceId: weekly.workspaceId,
      weekKey: weekly.weekKey,
      startsAt: weekly.startsAt?.toISOString() || null,
      endsAt: weekly.endsAt?.toISOString() || null,
      isAutoGenerated: weekly.isAutoGenerated,
      isClosed: weekly.isClosed,
      createdAt: weekly.createdAt.toISOString(),
    });
  } catch (error) {
    return handleApiError(error);
  }
}

export async function PATCH(request: NextRequest) {
  try {
    const url = new URL(request.url);
    const workspaceId = requireParam(url.searchParams.get('workspaceId'), 'workspaceId');
    const weekKey = requireParam(url.searchParams.get('weekKey'), 'weekKey');
    const isClosed = url.searchParams.get('isClosed');
    const closeValue = isClosed == null ? true : isClosed === 'true';

    const auth = await authorizeWorkspaceAccess(request, workspaceId, WorkspaceRole.EDITOR);
    if (!auth.ok) {
      return fail(auth.code, auth.message, auth.code === 'UNAUTHORIZED' ? 401 : 403);
    }

    const weekly = await findWeeklyEventByKey(workspaceId, weekKey);
    if (!weekly) {
      return fail('NOT_FOUND', 'Weekly event not found.', 404);
    }

    const updated = await prisma.event.update({
      where: { id: weekly.id },
      data: {
        isClosed: closeValue,
      },
    });

    invalidateServerCacheTags(Object.values(workspaceCacheTags(workspaceId)));

    return ok({
      id: updated.id,
      weekKey: updated.weekKey,
      isClosed: updated.isClosed,
      updatedAt: updated.createdAt.toISOString(),
    });
  } catch (error) {
    return handleApiError(error);
  }
}
